/**
 * Services Index
 * Unified API service exports
 * All API calls should go through these services
 */

// Auth
export { authService, authApi, type LoginRequest, type LoginResponse, type TokenResponse } from './auth.service'

// Category
export {
  categoryService,
  categoryApi,
  type Category,
  type CreateCategoryDto,
  type UpdateCategoryDto
} from './category.service'

// Tag
export { tagService, tagApi, type Tag, type CreateTagDto, type UpdateTagDto } from './tag.service'

// Export generated api from src/api (re-export existing modules)
// These are maintained separately as they're auto-generated by api2ts
